version: "3"
services:
  wishlistapi:
    build: .
    ports:
      - 4001:3000
    volumes:
      - .:/app
    command: sh -c "/wait && npm run knex:migrate:latest && npm install && npm run start:dev"
    environment:
      WAIT_HOSTS: db-dev:3306
    depends_on:
      - db-dev
  db-dev:
    image: mysql:5.7
    ports:
      - 33306:3306
    environment:
      MYSQL_USER: wishlist_dev
      MYSQL_PASSWORD: wishlist123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wishlist_development
